modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/FTBTeam/FTB-Essentials/issues"
license = "All Rights Reserved"

[[mods]]
modId = "ftbessentials"
version = "${version}"
displayName = "FTB Essentials"
authors = "LatvianModder"
description = '''
Adds many essential utility commands for servers
'''

[[dependencies.ftbessentials]]
modId = "forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbessentials]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbessentials]]
modId = "ftblibrary"
mandatory = true
versionRange = "[1605.3.4-build.79,)"
ordering = "NONE"
side = "BOTH"